# Generated by Django 4.2.21 on 2025-06-09 08:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20, verbose_name='股票代號')),
                ('name', models.CharField(max_length=100, verbose_name='股票名稱')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='當時單價')),
                ('quantity', models.PositiveIntegerField(verbose_name='千股單位數量')),
                ('total', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='總金額')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='下單時間')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '下單紀錄',
                'verbose_name_plural': '下單紀錄',
                'db_table': 'investments_orders',
            },
        ),
    ]
