# Generated by Django 4.2.21 on 2025-05-26 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='account_no',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True),
        ),
    ]
