# Generated by Django 4.2.21 on 2025-05-29 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_account_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='tx_type',
            field=models.CharField(choices=[('in', '收入'), ('out', '支出'), ('xfer', '轉帳')], default='out', max_length=4),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_no',
            field=models.CharField(max_length=14, unique=True),
        ),
    ]
