# Generated by Django 4.2.21 on 2025-05-29 15:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_transaction_tx_type_alter_account_account_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='tx_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
