# Generated by Django 4.2.21 on 2025-05-30 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_transaction_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('food', '餐飲'), ('shopping', '購物'), ('subscription', '訂閱'), ('bill', '帳單'), ('salary', '薪資'), ('other', '其他')], default='other', max_length=30),
        ),
    ]
